# Jekyll configuration for GitHub Pages
# Disable Jekyll processing for static HTML files

# Disable Jekyll processing
plugins: []

# Don't process files with these extensions
exclude:
  - .gitignore
  - README.md
  - DEPLOYMENT.md
  - AUDIO.md
  - FIXES.md
  - PROJECT_SUMMARY.md
  - .github/

# Don't use Jekyll's default processing
markdown: kramdown
highlighter: rouge

# Site settings
title: "TG3 Classic Tetris"
description: "Classic NES Tetris game with authentic physics and sound"
url: "https://jwtseng.github.io/AiCodex"
baseurl: ""

# Build settings
destination: _site
